source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SpotlightBeam_Example', :exclusive => true do
  pod "SpotlightBeam", :path => "../"
end

target 'SpotlightBeam_Tests', :exclusive => true do
  pod "SpotlightBeam", :path => "../"

  
end
